### ISSUE TITLE
Confirmation-Finisher vanishes

### ISSUE THREAD

**Issue by ZYZ64738** [frappant/frp_form_answers#18] opened 2018-10-30 15:38 UTC
Typo3: 8.7.19 AND 8.7.20
frp_form_answers: 1.1.0

... if "frp_form_answers" is installed

b4 installation ....

![image](https://user-images.githubusercontent.com/9817678/47730137-df3c2780-dc61-11e8-8642-7256ad77745b.png)

... and after  installation :+1: 
![image](https://user-images.githubusercontent.com/9817678/47730296-288c7700-dc62-11e8-8c8d-b606eae4568c.png)

**Comment by wini2** [comment] 2018-11-01 16:56
i can confirm this behaviour (8.7.18). 

While frp_form_answers is active, i can select "Confirmation message" from the add Finisher-Dropdown, but it doesn't. appear.

After i added the confimation text to the yaml-file directly, i receive an error 'Exception while property mapping at property path "": The value "Vielen Dank für Ihre Mithilfe. Zu Ihrere Infomation: Wir haben soeben eine E-Mail an die von Ihnen eingetragene Adresse gesendet, die die Inhalte des Formulars enthält." of property "options.message" (form element "abgleichMitgliedsdaten" / "finishers.Confirmation")'.

**Comment by wini2** [comment] 2018-11-12 19:15
seems to be fixed in v. 1.2.0 (TYPO3-Version 8.7.20).
thanks a lot

**Comment by Wh0l3** [comment] 2018-11-13 09:34
Yes, I tried to fix it - nice to hear that it worked for you. 
The Problem was the finisher number, wich overrode the Finisher "Bestätigungsmeldung"

**Closed by Wh0l3** 2018-11-13 09:34 UTC
